olimorris/persisted.nvim

lua/persisted/utils.lua
This PR fixes #18 by replacing the pattern match with an exact string match when determining if a directory matches in the `dirs_match()` function. This change will exclude patterns from being used in `allowed_dirs` and `ignored_dirs`, but I do not see anything in the README that indicates those directory names are meant to be patterns. If so, it should be stated in the README that any special lua pattern matching characters need to be properly escaped in the configuration with a `%` prefix.
=> Replace directory pattern match with exact match

lua/persisted/init.lua
This PR fixes #21 by using the `git rev-parse` command to determine if a directory is within a git repo instead of the presence of the `.git` directory which only works for the top level repo directory.
=> fix: #21 detect git-enabled directories with git command

lua/persisted/utils.lua
This PR fixes in issue described in [this comment](https://github.com/olimorris/persisted.nvim/pull/19#issuecomment-1214426942) where the directories in `allowed_dirs` and `ignored_dirs` can no longer be used as prefixes. By escaping all the special pattern matching characters in a directory name before using it has a pattern it will still work as a prefix but no characters will be interpreted as special pattern matches.
=> fix: #18 escape pattern matching characters in directory names

README.md, lua/persisted/config.lua, lua/persisted/init.lua
Add a configuration option for the string that's used to separate the session cwd from the git branch. This will facilitate easier parsing of the branch and cwd from the session file name in plugin callbacks.
=> feat: add configurable git branch separator string

README.md, lua/persisted/init.lua
Fixes #27 
Adds a hook for when `autoload = true` but there is no session to load.
=> Add `on_autoload_no_session` hook

README.md, lua/persisted/config.lua, lua/persisted/init.lua, lua/persisted/utils.lua, lua/telescope/_extensions/actions.lua
This PR add option to silent `nvim` message when sourcing session file.
Current behavior or when `silent = false` after sourcing session:
_message is printed, `:messages` has this message_
Behavior when `silent = true` after sourcing session:
_no message_
=> feat: add `silent` config option

README.md, lua/persisted/config.lua, lua/persisted/init.lua, tests/follow_cwd/follow_cwd_spec.lua, tests/minimal.vim
As discussed in #32, this adds a configuration option `follow_cwd` to allow or disallow session name changes on changes to the current working directory. It does so by adding a global variable `vim.g.persisting_session` that is either fixed for `follow_cwd=false` or `nil` for `follow_cwd=true`. 
By default, `follow_cwd=true` which will give the prior behavior.
=> Allow session name to be fixed on load

lua/persisted/init.lua, lua/telescope/_extensions/finders.lua, tests/minimal.vim
- Use telescope builtin resolver to calculate width.
- The branch is missing. Fixed.
- If session file stores without git branch, `session.branch` should be nil. And do not show branch in list.
- `make test` will fail because plenary.nvim is old.
close #34
=> fix(telescope): support width = { val, min, max } and show branch

README.md, lua/telescope/_extensions/persisted.lua
- Register `setup` hook to initialize options from Telescope setup.
- Remove unused `utils` variable. 
For example:
```lua
require('telescope').setup({
defaults = {
…
},
extensions = {
persisted = {
layout_config = { width = 0.55, height = 0.55 }
}
}
})
```
=> feat: Allow options to be set in Telescope setup

lua/persisted/init.lua
This assumes any lua special characters contained in the filepath (config.options.save_dir) is not to be treated as such.
Includes condition to try to format the session name on Windows OS.
=> fix: improve displayed session names

lua/persisted/init.lua
When nvim is used as a man pager with `export MANPAGER='nvim +Man! '`, with autoload set to true, persisted.nvim still autoloads the current directory which is not desirable
=> fix: prevent autoloading when there are extra command line arguments passed to nvim

lua/persisted/init.lua
**Problem:**    Shell programs aren't able to detect nvim exit.
**Solution:**   Avoid running shell-commands unnecessarily on exit.
_Tested with `opts = { autoload = true, follow_cwd = false }`_
Programs that spawn nvim in-order to edit a file are unable to detect nvim exit cleanly because of a race-condition that happens in `VimLeavePre` and `get_current()` which runs shell commands during exit even when `autosave` is off.
To reproduce, use nvim nightly, run persisted.nvim with:
```lua
opts.should_autosave = function()
-- Do not autosave if git commit/rebase session.
return vim.env.GIT_EXEC_PATH == nil
end
```
And run `EDITOR=nvim git commit` from shell; git will fail waiting for nvim to exit cleanly.
=> fix: unnecessary shell commands when autosave off

README.md, doc/persisted.nvim.txt, lua/persisted/utils.lua, tests/autoload/autoload_session_spec.lua
Per discussions in #98 here is my take on an exact `ignored_dirs`.
A side note, using a makefile for running tests and doc generation is so fucking smart, how have I not seen that before?
=> Added exact ignored_dirs support

README.md, doc/persisted.nvim.txt, lua/persisted/init.lua
The logic to prevent autoloading/starting sessions when any arguments are supplied to neovim is to prevent session management from kicking in when editing a single file.
This updates the logic to allow a single argument passed to neovim as long as the argument is an existing directory. When neovim is launched in this way it behaves the same as opening neovim with no arguments but has changed the working directory.
This results in consistent behavior of the autoloading/starting of sessions when passing a directory argument to start neovim.
See: https://github.com/olimorris/persisted.nvim/discussions/93
=> Update logic for autoload or starting sessions.

README.md, doc/persisted.nvim.txt, lua/persisted/init.lua
The `vim.loop.fs_realpath()` function can be used to properly resolve both the `.` shortcut as well as relative paths. This corrects scenarios when opening nvim to a subdirectory of the working directory. With this change doing so will properly resolve the session file to the directory that was specified on the command line.
```console
$ pwd
/Users/username/.config
$ ls
fish    iterm2    nvim
$ nvim nvim
```
This will result in using the path `/Users/username/.config/nvim` for the session. The behavior will be the same as running plain `nvim` from within the `/Users/username/.config/nvim` directory itself.
This change also quotes the path passed to `git` to properly handle paths containing spaces.
This change also corrects some typos in the readme.
=> fix: properly resolve directories

plugin/persisted.lua
When exiting neovim with this plugin active, I get a 134 exit code sporadically.
This is related to neovim/neovim#21856
This works around the issue with one of the suggestions in the aforementioned thread.
I imagine that at some point in the future, this will get resolved in neovim, and this workaround would not be needed. With that said, feel free to accept or reject this PR as you see fit.
=> Workaround for exit code 134 (neovim/neovim#21856)

doc/persisted.nvim.txt, lua/persisted/init.lua, lua/persisted/utils.lua
This changes the warning to print with vim.notify instead of printing to the console.
NOTE: This does _not_ change the error message function that prints to the console. Errors (IMO) should be a bit painful and not as easy to ignore so I didn't touch that.
=> Updated nvim_echo to instead use vim.notify

lua/persisted/utils.lua
in case ignored branches have been set and the current dir is not a git directory no more error messages will be thrown
=> fix: error message outside of git repo

README.md, doc/persisted.nvim.txt, lua/persisted/config.lua, lua/persisted/init.lua, lua/telescope/_extensions/persisted.lua, lua/telescope/_extensions/persisted/finders.lua
Prettier rendering in the telescope picker.
Note: This uses nerd-font icons right know, and yeah, it's probably not ideal as the only option. Maybe we can make this configurable?
=> feat: add icons and colors to telescope picker

lua/persisted/init.lua
i am not sure is this a platform issue,i am using archlinux with gnu-coreutils 9.5,the right command for getting last accessed date is ``stat -c %x [file]``
=> fix:use stat to last modified date

Makefile, lua/persisted/init.lua, tests/follow_cwd/follow_cwd_spec.lua, tests/minimal.vim
`follow_cwd and nil or session` always use `session` because the `true and nil` expression is evaluated to false
=> Fix follow_cwd option

lua/persisted/init.lua, lua/telescope/_extensions/persisted/actions.lua
Properly starts sessions loaded from another directory using Telescope. Crucially, this version compares the working directory of the session, not the working directory at the time of the session load, to the lists of allowed and ignored directories.
=> fix: properly start a session from Telescope

lua/persisted/utils.lua
I ran into an issue with the data not being provided during the PersistedLoad* autocmds, looks like its due to the lack of the branch_separator in my session file names, this passes all tests although not sure if its changing the behavior from intended
=> fix: missing autocmd data when no branch

lua/persisted/init.lua, lua/persisted/utils.lua
The `utils.dirs_match()` function is not expecting input directories to already be sanitized and can result in failure to properly detect matches with directories.
The `init.allowed_dir()` function is sanitizing the current working directory before passing as input to `utils.dirs_match()`, causing failure to detect match with the following setup on a macOS system:
```lua
allowed_dirs = {
'~/.config',
}
```
And invoking `nvim` while in `~/.config/nvim` working directory.
This change removes `init.cwd()` which is only ever used twice, one of which is incorrectly in `init.allowed_dir()`, the other in `init.current()`. This updates `init.current()` to sanitize the working directory as is needed, and updates `init.allowed_dir()` to use the unsanitized working directory.
=> fix: do not pass sanitized directories into utils.dirs_match

lua/persisted/init.lua, tests/dirs_spec.lua
Addresses #146 
Note, I don't really know how to write a test to properly address the change in logic applied here. However I did run `make` and all tests passed.
That said, its worth considering if this is how you want to address this issue or not :)
=> Added better handling for empty tables

lua/persisted/init.lua
Instead of calling a shell command, `persisted.delete()` calls a builtin vim function to delete the session. This removes any possible incompatibilities between shells.
=> decoupled SessionDelete from current command shell

lua/persisted/init.lua
On the 150th line of `init.lua`,
The `M.config` may be a typo and can be corrected by `config.
=> fix: correct "M.config" with config
